server:
  port: 8080

spring:
  codec:
    max-in-memory-size: 5MB
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters: #to remove duplicate response header this is filter we use
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
        #Apply this CORS rule to every route
          '[/**]':
            allowedOrigins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
           # Spring Cloud Gateway has an auto-discovery mode — it can auto-create routes for every service registered in Eureka using the service name as path prefix.
           #Here it's disabled because we r defining routes manually below.
      discovery:
        locator:
          enabled: false
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
          # If request path starts with-send to auth-service
            - Path=/api/auth/**,/oauth2/**,/login/**
        - id: auth-service-openapi
          uri: lb://auth-service
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - SetPath=/v3/api-docs
        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/api/rooms/**
        - id: room-service-openapi
          uri: lb://room-service
          predicates:
            - Path=/v3/api-docs/room
          filters:
            - SetPath=/v3/api-docs
        - id: message-service-rest
          uri: lb://message-service
          predicates:
            - Path=/api/messages/**
        - id: message-service-openapi
          uri: lb://message-service
          predicates:
            - Path=/v3/api-docs/message
          filters:
            - SetPath=/v3/api-docs
        - id: message-service-ws
          uri: lb:ws://message-service
          predicates:
            - Path=/ws/chat,/ws/chat/**
            #The ws:// prefix tells gateway to use WebSocket proxying
        - id: notification-service-ws
          uri: lb:ws://notification-service
          predicates:
            - Path=/ws/notifications,/ws/notifications/**
            #The ws:// prefix tells gateway to use WebSocket proxying
        - id: notification-service-rest
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: notification-service-openapi
          uri: lb://notification-service
          predicates:
            - Path=/v3/api-docs/notification
          filters:
            - SetPath=/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: /v3/api-docs-gateway
  swagger-ui:
    config-url: /v3/api-docs-gateway/swagger-config
    urls:
      - name: auth-service
        url: /v3/api-docs/auth
      - name: room-service
        url: /v3/api-docs/room
      - name: message-service
        url: /v3/api-docs/message
      - name: notification-service
        url: /v3/api-docs/notification

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
       # /actuator/health → is gateway alive? Used by Docker/Kubernetes health checks
#/actuator/info → app metadata
#/actuator/gateway → shows all registered routes, useful for debugging
